spring:
  security:
    user:
      name: admin
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/example
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: yangqian0916

  mail:
  host: smtp.qq.com
  port: 587
  username: 2547898936@qq.com #这里填你的邮箱
  password: ftoxrhgtyjmydiad #这里填你的授权码
  default-encoding: UTF-8

server:
  address: localhost
  port: 7780

mybatis-plus:
mapper-locations: classpath:/mapper/*.xml
