
spring:
  datasource:

    url: jdbc:mysql://localhost:3306/schema_01?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  application:
    name: demo_01

#    swagger2注释需要的...
  mvc:
    pathmatch:
        matching-strategy: ant-path-matcher

#  application:
#    name: springfox-swagger
#
#
#    # ===== 自定义swagger配置 ===== #
#  swagger:
#    enable: true
#    application-name: ${spring.application.name}
#    application-version: 1.0
#    application-description: springfox swagger 3.0整合Demo
#    try-host: http://localhost:${server.port}



server:
    port: 8080

